name: salvest_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc_concurrency: ^0.3.0
  bloc_test: ^10.0.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  flutter_zoom_drawer: ^3.2.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
