name: salvest_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc_concurrency: ^0.3.0
  bloc_test: ^10.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.5
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^19.1.0
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.0.17
  flutter_zoom_drawer: ^3.2.0
  flutterfire_cli: ^1.2.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  image_picker: ^1.1.2
  intl: 0.18.1
  local_auth: ^2.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
