// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1wcjxz5OPWPLd7jnOrAXtdY1K1Siy3J0',
    appId: '1:10212303261:web:914b60413614ffe4280f74',
    messagingSenderId: '10212303261',
    projectId: 'real-estate-investment-7aad8',
    authDomain: 'real-estate-investment-7aad8.firebaseapp.com',
    storageBucket: 'real-estate-investment-7aad8.firebasestorage.app',
    measurementId: 'G-9SJZ93VX7E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSCFCYgQdqK-27ZxOehALE0McF_dgOGIA',
    appId: '1:10212303261:ios:fdbe76dd98ed791c280f74',
    messagingSenderId: '10212303261',
    projectId: 'real-estate-investment-7aad8',
    storageBucket: 'real-estate-investment-7aad8.firebasestorage.app',
    iosBundleId: 'com.example.salvestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSCFCYgQdqK-27ZxOehALE0McF_dgOGIA',
    appId: '1:10212303261:ios:fdbe76dd98ed791c280f74',
    messagingSenderId: '10212303261',
    projectId: 'real-estate-investment-7aad8',
    storageBucket: 'real-estate-investment-7aad8.firebasestorage.app',
    iosBundleId: 'com.example.salvestApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkbE7z4YahOvzcHyQfB_N-89-JBLdJIo0',
    appId: '1:10212303261:android:452a53fd6d23a498280f74',
    messagingSenderId: '10212303261',
    projectId: 'real-estate-investment-7aad8',
    storageBucket: 'real-estate-investment-7aad8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1wcjxz5OPWPLd7jnOrAXtdY1K1Siy3J0',
    appId: '1:10212303261:web:421e58fe8ea5c07a280f74',
    messagingSenderId: '10212303261',
    projectId: 'real-estate-investment-7aad8',
    authDomain: 'real-estate-investment-7aad8.firebaseapp.com',
    storageBucket: 'real-estate-investment-7aad8.firebasestorage.app',
    measurementId: 'G-GXLRYXP3F4',
  );

}